### ISSUE TITLE
Apartments - Never load

### ISSUE THREAD

**Issue by JajarGaming** [nxxnly/SummitRP#3]
![image](https://user-images.githubusercontent.com/71441748/118088087-34c72280-b3cf-11eb-803c-49ee93ac820f.png)It just stays inside a black screen.

Edit:
![image](https://user-images.githubusercontent.com/71441748/118088217-663fee00-b3cf-11eb-9d58-01378a362457.png)
I reloaded the resource and this popped up.

**Comment by nxxnly** [comment]
i think apart needs housingshell to work.. do you have it ?

**Comment by JajarGaming** [comment]
nope, u have it?

**Comment by nxxnly** [comment]
closed... as I said this needs housingshells
